openapi: 3.0.3
info:
  title: API V1
  version: 1.0.0
paths:
  /api/v1/login:
    post:
      summary: Create a login session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
  /api/v1/create:
    post:
      summary: Create a session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                code:
                  type: integer
                token:
                  type: string
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                code:
                  type: integer
                token:
                  type: string
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
  /api/v1/destroy:
    post:
      summary: Delete a session
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
  /api/v1/products:
    get:
      summary: List products
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
  post:
    summary: Create a product
    requestBody:
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              full_description:
                type: string
              image:
                type: file
    responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
  /api/v1/products/{id}:
    get:
      summary: Show a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
    patch:
      summary: Update a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                full_description:
                  type: string
                image:
                  type: file
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
    delete:
      summary: Delete a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
  /api/v1/products/favourites:
    post:
      summary: Create a favorite product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                product_id:
                  type: integer
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                product_id:
                  type: integer
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
  /api/v1/products/favourites/{id}:
    delete:
      summary: Delete a favorite product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '400':
          description: Bad Request
servers:
  - url: http://localhost:3000
    variables:
      defaultHost:
        default: localhost:3000
